# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dbconnect.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 10, 431, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.label1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.horizontalLayout1.addWidget(self.label1)
        self.lineEdit1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit1.setObjectName("lineEdit1")
        self.horizontalLayout1.addWidget(self.lineEdit1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(70, 279, 421, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.pushButton1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton1.setObjectName("pushButton1")
        self.horizontalLayout2.addWidget(self.pushButton1)
        self.pushButton2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton2.setObjectName("pushButton2")
        self.horizontalLayout2.addWidget(self.pushButton2)
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(20, 320, 500, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 18))
        self.menubar.setObjectName("menubar")


        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # event
        self.pushButton1.clicked.connect(self.create_database)
        self.pushButton2.clicked.connect(self.db_connect)


    def create_database(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                port="3307"
            )
            cursor = mydb.cursor()
            dbname = self.lineEdit1.text()
            cursor.execute("CREATE DATABASE {}".format(dbname))
            self.label3.setText("Database () Created".format(dbname))
        except mc.Error as e:
            self.label3.setText("Database creation failed")

    def db_connect(self):
        mydb = mc.connect(
            host="localhost",
            user="root",
            password="",
            port="3307",
            database="db_penjualan_visual"
            )
        if mydb.is_connected():
            self.label3.setText("There is Connection")
        else:
            self.label3.setText("Error in Connection")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "CREATE DATABASE"))
        self.pushButton1.setText(_translate("MainWindow", "DATABASE CREATION"))
        self.pushButton2.setText(_translate("MainWindow", "DATABASE CONNCTION"))
        self.label3.setText(_translate("MainWindow", "TextLabel"))

class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent=parent)
        self.setupUi(self)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    w = MainWindow()
    w.show()
    sys.exit(app.exec_())